// <auto-generated />
using System;
using ControleEstoque.Infra.Mysql.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleEstoque.Infra.Mysql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ControleEstoque.DataModels.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CodigoItem")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("ControleEstoque.DataModels.Entities.Ordem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int>("NumeroOrdem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ordem", (string)null);
                });

            modelBuilder.Entity("ControleEstoque.DataModels.Entities.OrdemItens", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrdemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrdemId");

                    b.ToTable("OrdemItens", (string)null);
                });

            modelBuilder.Entity("ControleEstoque.DataModels.Entities.OrdemItens", b =>
                {
                    b.HasOne("ControleEstoque.DataModels.Entities.Item", "Item")
                        .WithMany("OrdemItens")
                        .HasForeignKey("ItemId")
                        .IsRequired();

                    b.HasOne("ControleEstoque.DataModels.Entities.Ordem", "Ordem")
                        .WithMany("OrdemItens")
                        .HasForeignKey("OrdemId")
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Ordem");
                });

            modelBuilder.Entity("ControleEstoque.DataModels.Entities.Item", b =>
                {
                    b.Navigation("OrdemItens");
                });

            modelBuilder.Entity("ControleEstoque.DataModels.Entities.Ordem", b =>
                {
                    b.Navigation("OrdemItens");
                });
#pragma warning restore 612, 618
        }
    }
}
